---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-lucid
  driver_config:
    box: lucid64
    box_url: http://files.vagrantup.com/lucid64.box

suites:
- name: default
  run_list:
    - recipe[read-the-docs::default]
